# Generated by Django 2.0.6 on 2018-08-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_ava'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ava',
        ),
    ]
