# Generated by Django 2.0.6 on 2018-09-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_profile_ava'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default='NOT DESCRIPTION', null=True),
        ),
    ]
